version: 2
jobs:
  build:
    working_directory: ~/question
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Install & lint & test
          environment:
            NG_CLI_ANALYTICS: "ci"
          command: |
            sudo npm install -g firebase-tools;
#            sudo npm install -g @angular/cli@latest;
#            ng lint;
#            ng test --code-coverage;
      - run:
          name: Prepare for deployment
          command: |
            if [ "${CIRCLE_BRANCH}" == "add-material" ];
            then rm src/environments/environment.prod.ts; mv src/environments/environment.feature.ts src/environments/environment.prod.ts;
            ng build --aot --prod --base-href https://aloha-feature.firebaseapp.com/; fi

            if [ "${CIRCLE_BRANCH}" == "master" ];
            then rm src/environments/environment.prod.ts; mv src/environments/environment.master.ts src/environments/environment.prod.ts;
            ng build --aot --prod --base-href https://aloha-master-67714.firebaseapp.com/; fi
      - run:
          name: Deploy app to firebase
          command: |
            if [ "${CIRCLE_BRANCH}" == "add-material" ]; then firebase deploy --project aloha-feature --token=$FIREBASE_DEPLOY_TOKEN; fi
            if [ "${CIRCLE_BRANCH}" == "master" ]; then firebase deploy --project aloha-master-67714 --token=$FIREBASE_DEPLOY_TOKEN; fi
workflows:
  version: 2
  workflow:
    jobs:
      - build
