version: 2
jobs:
  build:
    working_directory: ~/question
    docker:
      - image: circleci/node:15-browsers
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install --legacy-peer-deps
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Install tools & lint & test
          command: |
            sudo npm install -g firebase-tools;
            sudo npm install -g @angular/cli > /dev/null;
#            ng lint;
#            ng test --code-coverage ;
      - run:
          name: Prepare for deployment
          command: |
            if [ "${CIRCLE_BRANCH}" == "dev" ];
            then rm src/environments/environment.prod.ts; mv src/environments/environment.dev.ts src/environments/environment.prod.ts;
            ng build --aot --prod --base-href https://aloha-feature.firebaseapp.com/; fi

            if [ "${CIRCLE_BRANCH}" == "prod" ];
            then ng build --aot --prod --base-href https://thicongchuc.org/; fi
      - run:
          name: Deploy app to firebase
          command: |
            if [ "${CIRCLE_BRANCH}" == "dev" ]; then firebase deploy --project aloha-feature --token=$FIREBASE_DEPLOY_TOKEN; fi
            if [ "${CIRCLE_BRANCH}" == "prod" ]; then firebase deploy --project thicongchuc-22e3a --token=$PROD_FIREBASE_DEPLOY_TOKEN; fi
workflows:
  version: 2
  workflow:
    jobs:
      - build
